### ISSUE TITLE
Plug-in randomly freezing forcing to reboot

### ISSUE THREAD

**Issue by jeregon1** [DucNg/digitalclock.koplugin#7]
Tonight I've left it all night and it has randomly frozen at 8:01 and now it has frozen after 20min at 9:11.

By frozen I mean that it won't respond to touches or gestures or even the on/off button on the kindle (PW 11th gen) so the only thing I can do is reboot it long pressing the button.

Any ideas why it could happen?

**Comment by DucNg** [comment]
Yeah it did happened to me, several possibilities:

* Your device ran out of battery: sometimes your device run out of battery and the screen just freeze without any other message. It just keeps displaying the last screen.
* `preventScreenSaver` is in an "unstable" state, your device thinks it's in sleep mode but you can't exit even with the power button:
  * You've used clock.koplugin: delete it from your device and do a full reboot
  * Your device ran out of battery while on digitalclock.koplugin, preventScreenSaver 0 wasn't properly called: do a full reboot of your device
  * There is a bug in digitalclock.koplugin that cause preventScreenSaver 0 not to be called: do a full reboot of your device
  * You've used the keepalive plugin: same
  * Make sure you start koreader without amazon framework

Whenever you encounter something strange like this, do a full reboot (don't just restart koreader), it usually fixes the issue for me. Please try and tell me if it works for you.

**Comment by jeregon1** [comment]
I've made sure that all of those were true:
- clock.koplugin is not installed
- keepalive plugin is disabled

  *
My device has not run out of battery
  *
I've started koreader without framework
  *
I've rebooted the device after each of these steps

Still it freezes some time after using the plugin.
________________________________

**Comment by DucNg** [comment]
Thanks for double checking this. It seems like the `preventScreenSaver` is not working properly on your device.

Just one last time, are you sure you've properly rebooted your device from the "reboot" button on the "power modal" of the Amazon framework? **Not inside koreader and not using the long press on the power button**

If it still doesn't work, I'm not sure I can help you any further, I don't have access to a PW 11th gen so you'll have to do testing on your own. It's working fine on my PW3.

You can try with the code of this branch: https://github.com/DucNg/digitalclock.koplugin/pull/8

It's an attempt to use the generic pause auto suspend instead of calling the Kindle specific function directly. I'm really unsure if that will help in any way but you can give it a try.

To do further investigation I will need to have access to some debug logs. As I never needed this I didn't look on how to do it. Again, you'll have to figure out a way to do it on your own. With debug logs, maybe I can investigate a bit further.

**Comment by jeregon1** [comment]
Ok, every time I rebooted it was by long pressing the power button... I'll try it, thanks for the clarification 😅

Edit: I've properly rebooted it as you said and yet again after roughly 25m it has frozen the device. I'll later try that branch, thanks for the efforts

Edit 2: It's come to mind that I have the [dtdisplay](https://github.com/kktse/dtdisplay.koplugin) plugin installed, maybe it interferes? I don't know, but I've tried disabling it and rebooting and it still freezes. Is it necessary to delete de plugin files rather than disabling it?

**Comment by DucNg** [comment]
>Is it necessary to delete de plugin files rather than disabling it?

Yes, from my experience, you need to delete the files as some code from plugins is ran when koreader starts.

**Comment by DucNg** [comment]
It's not a device issue but a KOReader version issue.

I just upgraded koreader to 2025.10 and I was able to reproduce the bug. The issue doesn't seem to be present on 2025.08. Try it and tell me if it works for you.

In the mean time I will try to ask KOReader team what could have caused the regression.

**Comment by jeregon1** [comment]
I've installed 2025.08 and it works flawlessly now, what a relief!

Thanks for finding out, I hope they can fix it easily

**Comment by DucNg** [comment]
Thanks for renaming the issue. 👍 

It should be fixed in the next release of koreader, I'm pretty sure it's the same problem as this: https://github.com/koreader/koreader/issues/14548

**Comment by jeregon1** [comment]
https://github.com/koreader/koreader/issues/14548 has been fixed, so let's assume this issue is closed, as far as I've tested.

**Comment by jeregon1** [comment]
Well, a couple of hours after updating, the issue is here again...

**Comment by DucNg** [comment]
> Well, a couple of hours after updating, the issue is here again...

I tried the nightly build a while back and I saw that the issue was still there. Thanks for testing with the new release as well!

Maybe it's time to retry with this fix now: https://github.com/DucNg/digitalclock.koplugin/pull/8 (back then it didn't fix it)

**Comment by jeregon1** [comment]
Sadly, I've tried that fix with the update but it didn't solve the issue. 

I applied the fix and then rebooted from the Amazon framework Reboot button, not by long pressing the sleep physical button. Then I gave it a go. It's a pity!

**Comment by DucNg** [comment]
Thanks for taking the time to test this 🙏 

I will open an issue on the main KOReader repo to see if anyone has an idea of what's going on.

**Comment by jeregon1** [comment]
So, I've noticed something curious which has led to this plugin behaving exactly as it should on KOreader's latest patch in my Kindle PW 11th gen.

After noticing the KO bug was still kicking in latest patch, I decided I'd turn off autosuspend in KO because I actually never let it autosuspend itself. I did this for the sake of getting the KO updates and using this plugin at the same time without getting crashes. 

So what I found out was that the Kindle's native autosuspend feature kicked in because KO doesn't seem to disable it when its autosuspend timeout toggle is disabled, and thus my kindle autosuspended after 5 minutes of inactivity.

But! This plugin's code works perfectly at disabling that Kindle's native autosuspend feature. So I can select the timeout I want in Amazon's framework (in fact the timeout can't be disabled) and still hace this plugin prevent the device from sleeping).


Sorry for the length, but now I don't know if this is still an issue or what we can derive from it other than KO not interacting very well with the Kindle.
